/**
 * Hyperapp micro rewrite demo on React Native
 *
 * based on code generated by react-native init
 *
 * https://github.com/facebook/react-native
 *
 * @flow
 */

import React from 'react'

import createReactClass from 'create-react-class'

import {
  Button,
  StyleSheet,
  Text,
  View
} from 'react-native'

const initState = {count: 0}

const actions = {
    increase: (value) => (state) => ({ count: state.count + value }),
    decrease: (value) => (state) => ({ count: state.count - value }),
}

const renderAppView =
  (state, actions) => {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Hyperapp micro rewrite demo on React Native
        </Text>
        <Button
          onPress={() => actions.increase(1)}
          title="Up (+1)"
        />
        <Text style={styles.welcome}>
          {state.count}
        </Text>
        <Button
          onPress={() => actions.decrease(1)}
          title="Down (-1)"
        />
      </View>
    )
  }

const App = () => (
  <ManagedView state={initState} actions={actions} renderView={renderAppView} />
)

export default App

const ManagedView = createReactClass({
  getInitialState() {
    const ac = {}
    const self = this
    for (let a in this.props.actions) ac[a] = (v) => {
      self.setState(prev => ({ac: ac, st: (this.props.actions[a](v)(prev.st))}))
    }
    return {ac: ac, st: this.props.state}
  },
  render() {
    return this.props.renderView(this.state.st, this.state.ac)
  }
})

// from react-native init:
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
})
