/**
 * Hyperapp micro rewrite demo on React Native
 *
 * based on code generated by react-native init
 *
 * https://github.com/facebook/react-native
 *
 * @flow
 */

import React, { Component } from 'react'

import {
  Button,
  StyleSheet,
  Text,
  View
} from 'react-native'

const initState = {count: 0}

const actions = {
    increase: (value) => (state) => ({ count: state.count + value }),
    decrease: (value) => (state) => ({ count: state.count - value }),
}

const renderAppView =
  (state, actions) => {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Hyperapp micro rewrite demo on React Native
        </Text>
        <Button
          onPress={() => actions.increase(1)}
          title="Up (+1)"
        />
        <Text style={styles.welcome}>
          {state.count}
        </Text>
        <Button
          onPress={() => actions.decrease(1)}
          title="Down (-1)"
        />
      </View>
    )
  }

export default class App extends Component<{}> {
  constructor(props) {
    super(props)

    this.state = initState

    const self = this
    this.actions = {}
    for (let a in actions) this.actions[a] = (v) => {
      self.setState(prevState => (actions[a](v)(prevState)))
    }
  }
  render() {
    return renderAppView(this.state, this.actions)
  }
}

// from react-native init:
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
})
